name: asciidoctor-ghpages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  asciidoctor-ghpages:
    runs-on: ubuntu-latest
    steps:
    - uses: manoelcampos/asciidoctor-ghpages-action@v2
